<div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('Ainstainer contact') ?></h1>
</div>
<!--<div>--><?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact_gmap')->toHtml(); ?><!--</div>-->

<form action="<?php echo $this->getUrl('*/*/save'); ?>" id="contactForm" method="post" class="scaffold-form">
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Contact Information') ?></h2>
        <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                    <div class="input-box">
                        <input name="name" id="name" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>"
                               class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="name" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('E-mail') ?></label>
                    <div class="input-box">
                        <input name="email" id="email" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="tel"><?php echo Mage::helper('contacts')->__('Phone') ?></label>
                    <div class="input-box">
                        <input name="tel" id="tel" class="input-text" type="text" />
                    </div>
                </div>
                <div class="field">
                    <label for="description" class="required"><em>*</em><?php echo Mage::helper('contacts')->__('Description') ?></label>
                    <div class="input-box">
                        <textarea name="description" id="description" class="input-text required-entry"></textarea>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <button type="submit" class="button"><?php echo Mage::helper('contacts')->__('Submit') ?></button>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
    //]]>
</script>
</form>