<?php if (($banners = $this->getBannerCollection()) && $banners->getSize()): ?>

    <div id="slider-wrap">
        <div id="slider">
            <?php foreach ($banners->getItems() as $banner): ?>
                <div class="slide">
                    <a href="<?=$banner->getUrl()?>" target="_blank">
                        <img alt='' title="<?=$banner->getDescription();?>"
                             src="<?=$banner->getImage();?>" height="100%" width="100%" />
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

<?php endif; ?>